name: pip testing sentiment analysis

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'
    
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      # shell: pwsh  # Use PowerShell
      # run: |
      #  if (Test-Path API/requirements.txt) {
      #    pip install -r API/requirements.txt
      #  }
      run: pip install -r API/requirements.txt
    - name: Test with pytest
      env:
        PYTHONIOENCODING: utf-8
      run: pytest -s
